version: '1.0'
stages:
  - prepare
  - test
  - package
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'kurumai/circleci-demo-java-spring'
    revision: ci-tools
    git: github
  Test:
    title: Compile/Unit test
    stage: test
    image: openjdk:11.0.3-jdk-stretch
    services:
      name: postgres
      composition:
        postgres:
          image: postgres:12-alpine
          environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=circle_test
          ports:
            - 5432
    commands:
      - ./gradlew build -x test
      - ./gradlew test --no-daemon --build-cache
      - ./gradlew jacocoTestReport
  BuildMyJar:
    title: Packaging Jar file
    stage: package
    image: gradle:5.5-jdk11
    commands:
      - gradle build --no-daemon --build-cache --gradle-user-home=/codefresh/volume/.gradle -Dmaven.repo.local=/codefresh/volume/m2