version: '1.0'
services:
  name: postgres
  composition:
    my-redis-db-host:
      image: postgres:12-alpine
      ports:
        - 5432
stages:
  - prepare
  - test
  - package
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'kurumai/circleci-demo-java-spring'
    revision: actions
    git: github
  Test:
    title: Compile/Unit test
    stage: test
    image: gradle:5.5.0-jdk8-alpine
    commands:
      - gradle test --no-daemon --build-cache --gradle-user-home=/codefresh/volume/.gradle -Dmaven.repo.local=/codefresh/volume/m2
  BuildMyJar:
    title: Packaging Jar file
    stage: package
    image: gradle:5.5.0-jdk8-alpine
    commands:
      - gradle build --no-daemon --build-cache --gradle-user-home=/codefresh/volume/.gradle -Dmaven.repo.local=/codefresh/volume/m2