version: '1.0'
stages:
  - prepare
  - test
steps:
  dependencies:
    title: dependencies
    stage: prepare
    type: git-clone
    repo: 'kurumai/circleci-demo-java-spring'
    revision: ci-tools
    git: github
    commands:
      - ./gradlew build -x test --no-daemon --build-cache --gradle-user-home=/codefresh/volume/.gradle -Dmaven.repo.local=/codefresh/volume/m2
  test:
    title: test
    stage: test
    image: gradle:jdk11
    services:
      name: postgres
      composition:
        postgres:
          image: postgres:12-alpine
          environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=circle_test
          ports:
            - 5432
    commands:
      - ./gradlew test --no-daemon --build-cache --gradle-user-home=/codefresh/volume/.gradle -Dmaven.repo.local=/codefresh/volume/m2
      - ./gradlew jacocoTestReport
      - ./gradlew assemble

      